import { useRecoilState, useEffect } from '../libraries';
import { newsState, newsSelector } from '../atoms';

import Head from 'next/head';
import AppLayout from '../components/templates/AppLayout';

export default function Home({ newsResults, randomUsersResults }) {
  // console.log(newsResults.articles);
  // console.log(randomUsersResults.results);
  const [news, setNewsState] = useRecoilState(newsState); // 전역상태를 state로 만듦
  // const [users, setUsersState] = useRecoilState(randomUsersResults.results); // 전역상태를 state로 만듦

  // console.log('index1', news);
  // console.log('index2', users);

  useEffect(() => {
    if (newsResults.articles) {
      setNewsState(newsResults.articles);
    }
  }, []);

  return (
    <div>
      <Head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Next App v1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout
        mode={'dev'}
        title="Homepage"
        description="Ini Description Homepage"
        showLeftSidebar={true}
        showRightSidebar={true}
        showHeader={true}
        showFooter={true}
      >
        {/* <nav className="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">
          <div className="container-fluid">
            <a className="navbar-brand" href="#">
              Sticky top
            </a>
          </div>
        </nav> */}
        {[...Array(100)].map((x, i) => (
          <p key={i}>test {i}</p>
        ))}
        <div>test11</div>
        <div>test22</div>
      </AppLayout>
    </div>
  );
}
// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
export async function getStaticProps() {
  const newsResults = await fetch('https://saurav.tech/NewsAPI/everything/cnn.json').then((res) =>
    res.json(),
  );

  let randomUsersResults = [];

  try {
    const res = await fetch('https://randomuser.me/api/?results=30&inc=name,login,picture');

    randomUsersResults = await res.json();
  } catch (e) {
    randomUsersResults = [];
  }

  // console.log('getServerSideProps', newsResults);

  return {
    props: {
      newsResults,
      randomUsersResults,
    },
  };
}
