import Head from 'next/head';
import AppLayout from '../components/templates/AppLayout';

export default function Home() {
  return (
    <div>
      <Head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Next App v1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout
        mode={'dev'}
        title="Homepage"
        description="Ini Description Homepage"
        showLeftSidebar={true}
        showRightSidebar={true}
        showHeader={true}
        showFooter={true}
      >
        {/* <nav className="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">
          <div className="container-fluid">
            <a className="navbar-brand" href="#">
              Sticky top
            </a>
          </div>
        </nav> */}
        {[...Array(100)].map((x, i) => (
          <p key={i}>test {i}</p>
        ))}
        <div>test11</div>
        <div>test22</div>
      </AppLayout>
    </div>
  );
}
